# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_question_name', models.CharField(max_length=1000)),
                ('p_question_files', models.FileField(upload_to='')),
                ('p_question_description', models.TextField(max_length=10000)),
                ('p_category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.PracticeCategory')),
            ],
        ),
    ]
