# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='p_question_points',
            field=models.IntegerField(default=0),
        ),
    ]
