# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practicequestion_p_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='p_question_flag',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
